name: Build Flutter APK & AAB from ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Extract ZIP
        run: unzip nw9to_project_supabase_email_full_v2_cleaned.zip -d project

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: Fix intl version
        run: cd project && flutter pub add intl:^0.19.0

      - name: Install dependencies
        run: cd project && flutter pub get

      - name: Build APK (release)
        run: cd project && flutter build apk --release

      - name: Build AAB (release)
        run: cd project && flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: project/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: project/build/app/outputs/bundle/release/app-release.aab
